image: docker:19
services:
  - docker:19-dind

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

maven-build:
  image: maven:3.6.3-jdk-11
  stage: build
  tags:
    - ILT
  script: "mvn verify -B -s ci_settings.xml"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: deploy
  tags:
    - ILT
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN https://gitlab-ext.iosb.fraunhofer.de:4567
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      -f ./services/spring/spring.dockerfile
      -
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
