include:
  - remote: https://ci-templates.k8s.ilt-dmz.iosb.fraunhofer.de/templates/gitlab-ci-common.yml

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  ARTIFACT_ID: backend
  VERSION: 0.0.1-SNAPSHOT
  K8S_NAMESPACE: pse-reskue
  APPLICATION_PORT: 8080
  K8S_KUSTOMIZE_PATH: services/k8s

default:
  tags:
    - ILT

stages:
  - build
  - push
  - deploy

maven-build:
  image: gitlab-ext.iosb.fraunhofer.de:4567/ilt-pse/ws20_21-mobile-anwendung-zur-unterst-tzung-im-kulturg-terschutz/kueres-backend/maven-docker-compose-cli:openjdk-11
  stage: build
  script: "mvn verify -Dmaven.test.skip=true -B -s ci_settings.xml"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  extends:
    - .docker-build-common
  stage: push
  only:
    - branches
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull  $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --build-arg ARTIFACT_ID=$ARTIFACT_ID
      --build-arg VERSION=$VERSION
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
      --file services/spring/spring.dockerfile
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH

deploy_staging:
  extends: 
    - .deploy
  variables:
    DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}${DOCKER_IMAGE_SUBPROJECT}:$CI_COMMIT_REF_SLUG
  environment:
    name: staging/$CI_COMMIT_REF_NAME
    url: ${K8S_PROTOCOL}${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}.${K8S_BASE_URL}
  only:
    - master

undeploy_staging:
  extends: 
    - .undeploy_staging

get_logs:
  stage: build
  extends:
    - .deploy-before
    - .when_manual
  script:
    - kubectl get deployments
    - kubectl logs deployment/reskue-backend-staging-master-ke8rgq
