variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  ARTIFACT_ID: backend
  VERSION: 0.0.1-SNAPSHOT

stages:
  - build
  - deploy

maven-build:
  image: gitlab-ext.iosb.fraunhofer.de:4567/ilt-pse/ws20_21-mobile-anwendung-zur-unterst-tzung-im-kulturg-terschutz/kueres-backend/maven-docker-compose-cli:openjdk-11
  stage: build
  tags:
    - ILT
  script: "mvn verify -Dmaven.test.skip=true -B -s ci_settings.xml"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  image: docker:18.09
  services:
  - docker:18.09.7-dind
  stage: deploy
  tags:
    - ILT
  only:
    - master
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull  $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --build-arg ARTIFACT_ID=$ARTIFACT_ID
      --build-arg VERSION=$VERSION
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
      --file services/spring/spring.dockerfile
      .
    - docker push $CI_REGISTRY_IMAGE:latest
