include:
  - remote: https://ci-templates.docker01.ilt-dmz.iosb.fraunhofer.de/templates/gitlab-ci-common.yml
  - remote: https://ci-templates.k8s.ilt-dmz.iosb.fraunhofer.de/templates/default/gitlab-ci-k8s-deploy-staging.yml

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  ARTIFACT_ID: backend
  VERSION: 0.0.1-SNAPSHOT
  K8S_NAMESPACE: pse-reskue
  APPLICATION_PORT: 8080
  K8S_KUSTOMIZE_PATH: services/k8s

default:
  tags:
    - ILT

stages:
  - build
  - deploy

maven-build:
  image: maven:3.6.3-jdk-11
  stage: build
  script: "mvn verify -B -s ci_settings.xml"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  image: docker:18.09
  services:
  - docker:18.09.7-dind
  stage: deploy
  only:
    - master
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull  $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --build-arg ARTIFACT_ID=$ARTIFACT_ID
      --build-arg VERSION=$VERSION
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
      --file services/spring/spring.dockerfile
      .
    - docker push $CI_REGISTRY_IMAGE:latest