/'
Syntax documentation:
https://plantuml.com/de/class-diagram
'/
@startuml reskue.backend
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

package "reskue.backend" as backend {

  !include BackendApplication.plantuml!0

  !include ../reskue.backend.entities/reskue.backend.entities.plantuml!0

  !include ../reskue.backend.rabbitmq/reskue.backend.rabbitmq.plantuml!0

  !include ../reskue.backend.keycloak/reskue.backend.keycloak.plantuml!0

  !include ../reskue.backend.error/reskue.backend.error.plantuml!0

  BaseService --|> EventSubscriber

  BackendApplication -[hidden]-> entities
  entities -[hidden]-> keycloak
  top to bottom direction
  BackendApplication -[hidden]-> error
  keycloak -[hidden]-> rabbitmq
}

@enduml