apiVersion: v1
kind: Service
metadata:
  name: reskue-keycloak
  labels:
    app: reskue-keycloak
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: reskue-keycloak