apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescue_keycloak
  labels:
    app: rescue_keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rescue_keycloak
  template:
    metadata:
      labels:
        app: rescue_keycloak
    spec:
      imagePullSecrets:
        - gitlab-ext
      containers:
      - name: app
        image: jboss/keycloak:latest
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        env:
          - name: DB_VENDOR
            value: POSTGRES
          - name: DB_ADDR
            value: auth-db
          - name: DB_PORT
            value: '5432'
          - name: DB_DATABASE
            value: auth_db
          - name: DB_SCHEMA
            value: public
          - name: DB_USER
            value: ''
          - name: DB_PASSWORD
            value: ''
          - name: KEYCLOAK_USER
            value: ''
          - name: KEYCLOAK_PASSWORD
            value: ''
          - name: KEYCLOAK_IMPORT
            value: ./tmp/realm-export.json

##Todo: Mount ream-config
