apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - templates/k8s/base
  - templates/k8s/overlays/rancher

patchesStrategicMerge:
  - deployment_envs.yaml
  - keycloak_deployment.yaml
  - keycloak_ingess.yaml
  - keycloak_service.yaml