@startuml DemoEntity

class DemoEntity {
  @Entity
  --
  - @Column(name = "name", nullable = false) name: String
  + {static} NAME: String
  + {static} NAME_MAPPING: String
  - @Column(name = "description", nullable = false) description: String
  + {static} DESCRIPTION: String
  + {static} DESCRIPTION_MAPPING: String
  --
}
DemoEntity : + getName(): String
DemoEntity : + setName(name: String): void
DemoEntity : + getDescription(): String
DemoEntity : + setDescription(description: String): void
DemoEntity : + @Override applyPatch(patch: DemoEntity): void

@enduml