@startuml reskue.backend.entities.demo
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50
top to bottom direction

package "reskue.backend.entities.demo" as demo {

  !include DemoController.plantuml!0
  !include DemoService.plantuml!0
  !include DemoRepository.plantuml!0
  !include DemoEntity.plantuml!0

  DemoController -[hidden]-> DemoService
  DemoService -[hidden]-> DemoRepository
  DemoRepository -[hidden]-> DemoEntity

}

@enduml