@startuml BaseController

class BaseController<E extends BaseEntity<E>, R extends BaseRepository<E>, S extends BaseService<E, R>> {
  + {static} API_ENDPOINT: String
  # @Autowired service: S
}
BaseController : + @GetMapping() findAll(): List<E>
BaseController : + @GetMapping(BaseEntity.ID_MAPPING) findById(@PathVariable(value = BaseEntity.ID) id: long): ResponseEntity<E>
BaseController : + @PostMapping() create(@Valid @RequestBody entity: E): E
BaseController : + @PutMapping(BaseEntity.ID_MAPPING) update(@PathVariable(value = BaseEntity.ID) id: long, @Valid @RequestBody details: E): ResponseEntity<E>
BaseController : + @DeleteMapping(BaseEntity.ID_MAPPING) delete(@PathVariable(value = BaseEntity.ID) id: long): Map<String, Boolean>

@enduml