@startuml reskue.backend.entities
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

package "reskue.backend.entities" as entities {

  !include BaseController.plantuml!0
  !include BaseService.plantuml!0
  !include BaseRepository.plantuml!0
  !include BaseEntity.plantuml!0

  BaseController -- BaseService
  BaseService -- BaseRepository
  BaseRepository --|> JpaRepository

  top to bottom direction
  BaseController -[hidden]-> BaseService
  BaseService -[hidden]-> BaseRepository
  BaseRepository -[hidden]-> BaseEntity
  left to right direction

  !include ../reskue.backend.entities.demo/reskue.backend.entities.demo.plantuml!0
  !include ../reskue.backend.entities.test/reskue.backend.entities.test.plantuml!0

  DemoController -up-|> BaseController
  DemoService -up-|> BaseService
  DemoRepository -up-|> BaseRepository
  DemoEntity -up-|> BaseEntity

  TestController -up-|> BaseController
  TestService -up-|> BaseService
  TestRepository -up-|> BaseRepository
  TestEntity -up-|> BaseEntity

}

@enduml