@startuml TestController

class TestController {
  @RestController
  @RequestMapping(BaseController.API_ENDPOINT + TestController.ROUTE)
  --
  + {static} IDENTIFIER: String
  + {static} ROUTE: String
  + {static} ROUTING_KEY: String
}

@enduml