@startuml TestEntity

class TestEntity {
  @Entity
  --
  - @Column(name = "name", nullable = false) name: String
  + {static} NAME: String
  + {static} NAME_MAPPING: String
  - @Column(name = "description", nullable = false) description: String
  + {static} DESCRIPTION: String
  + {static} DESCRIPTION_MAPPING: String
  --
}
TestEntity : + getName(): String
TestEntity : + setName(name: String): void
TestEntity : + getDescription(): String
TestEntity : + setDescription(description: String): void
TestEntity : + @Override applyPatch(patch: TestEntity): void

@enduml