@startuml EventConfiguration

class EventConfiguration {
  @Configuration
  --
  + {static} TOPIC_EXCHANGE: String
  + {static} QUEUE: String
  --
}
EventConfiguration : @Bean queue(): Queue
EventConfiguration : @Bean exchange(): TopicExchange
EventConfiguration : @Bean binding(queue: Queue, exchange: TopicExchange): Binding
EventConfiguration : @Bean container(connectionFactory: ConnectionFactory, listenerAdapter: MessageListenerAdapter): SimpleMessageListenerContainer
EventConfiguration : @Bean listenerAdapter(consumer: EventConsumer): MessageListenerAdapter
EventConfiguration : @Bean amqpAdmin(connectionFactory: ConnectionFactory): AmqpAdmin

@enduml