@startuml reskue.backend.keycloak
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50

namespace "reskue.backend.keycloak" as keycloak {

  !include KeycloakSecurityConfig.plantuml!0

  KeycloakSecurityConfig -up-|> KeycloakWebSecurityConfigurerAdapter

}

@enduml